name: deploy_website
on:
  push:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Edit README
        run: |
          sudo apt-get install -y -q python3
          sudo python3 main.py
      - name: Add & Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Edit README"
          git pull 
          git push
